import { useEffect, useState } from "react";
import { useSearchParams } from "react-router-dom";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/contexts/AuthContext";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Card } from "@/components/ui/card";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { toast } from "sonner";
import { Plus, Search, Trash2, Upload, Download, FileSpreadsheet, ExternalLink } from "lucide-react";
import { cn } from "@/lib/utils";
import { Link } from "react-router-dom";

interface Asset {
  id: string; code: string; name: string; status: string;
  description: string | null; serial_number: string | null;
  department_id: string; item_type_id: string;
  current_holder: string | null; current_location_id: string | null;
}
interface Dept { id: string; code: string; name: string; is_storage?: boolean; }
interface ItemType { id: string; code: string; name: string; }
interface Holder { id: string; display_name: string; }

export default function Assets() {
  const { isAdmin } = useAuth();
  const [searchParams] = useSearchParams();
  const initialStatus = searchParams.get("status") || "all";

  const [assets, setAssets] = useState<Asset[]>([]);
  const [depts, setDepts] = useState<Dept[]>([]);
  const [items, setItems] = useState<ItemType[]>([]);
  const [holders, setHolders] = useState<Record<string, string>>({});
  const [q, setQ] = useState("");
  const [statusFilter, setStatusFilter] = useState<string>(initialStatus);
  const [open, setOpen] = useState(false);
  const [importOpen, setImportOpen] = useState(false);
  const [csvText, setCsvText] = useState("");
  const [importing, setImporting] = useState(false);

  // form
  const [name, setName] = useState("");
  const [description, setDescription] = useState("");
  const [serial, setSerial] = useState("");
  const [deptId, setDeptId] = useState("");
  const [itemId, setItemId] = useState("");

  const load = async () => {
    const [{ data: a }, { data: d }, { data: i }, { data: p }] = await Promise.all([
      supabase.from("assets").select("*").order("code"),
      supabase.from("departments").select("*").order("name"),
      supabase.from("item_types").select("*").order("name"),
      supabase.from("profiles").select("id, display_name"),
    ]);
    setAssets(a ?? []);
    setDepts(d ?? []);
    setItems(i ?? []);
    setHolders(Object.fromEntries((p ?? []).map((x: Holder) => [x.id, x.display_name])));
  };
  useEffect(() => { load(); }, []);

  const filtered = assets.filter((a) => {
    const matchesQ = !q || a.code.toLowerCase().includes(q.toLowerCase()) || a.name.toLowerCase().includes(q.toLowerCase());
    const matchesS = statusFilter === "all" || a.status === statusFilter;
    return matchesQ && matchesS;
  });

  const create = async () => {
    if (!name || !deptId || !itemId) {
      toast.error("Name, department and item type are required");
      return;
    }
    const dept = depts.find((d) => d.id === deptId);
    const { error } = await supabase.from("assets").insert({
      name, description: description || null, serial_number: serial || null,
      department_id: deptId, item_type_id: itemId,
      current_location_id: depts.find((d) => d.is_storage)?.id ?? deptId,
      code: "", // generated by trigger
    } as any);
    if (error) { toast.error(error.message); return; }
    toast.success(`Asset registered in ${dept?.name}`);
    setOpen(false);
    setName(""); setDescription(""); setSerial(""); setDeptId(""); setItemId("");
    load();
  };

  const remove = async (id: string) => {
    if (!confirm("Delete this asset permanently?")) return;
    const { error } = await supabase.from("assets").delete().eq("id", id);
    if (error) { toast.error(error.message); return; }
    toast.success("Asset deleted");
    load();
  };

  // ----- CSV BULK IMPORT -----
  const csvHeader = "Asset Code,Division,Description,Serial Number,Location,Image URL";
  const csvSample = `${csvHeader}\nAJ001,Aircon,Jet Air 12000btu Split unit,SN12345,Centurion,/assets/photos/sample.jpg`;

  const downloadTemplate = () => {
    const blob = new Blob([csvSample], { type: "text/csv" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "assets-template.csv";
    a.click();
    URL.revokeObjectURL(url);
  };

  const onCsvFile = async (file: File) => {
    if (file.size > 2 * 1024 * 1024) {
      toast.error("File too large (max 2MB)");
      return;
    }
    const text = await file.text();
    setCsvText(text);
  };

  const parseCsv = (text: string): string[][] => {
    const rows: string[][] = [];
    let row: string[] = [];
    let cur = "";
    let inQuotes = false;
    for (let i = 0; i < text.length; i++) {
      const ch = text[i];
      if (inQuotes) {
        if (ch === '"' && text[i + 1] === '"') { cur += '"'; i++; }
        else if (ch === '"') { inQuotes = false; }
        else { cur += ch; }
      } else {
        if (ch === '"') inQuotes = true;
        else if (ch === ",") { row.push(cur); cur = ""; }
        else if (ch === "\n") { row.push(cur); rows.push(row); row = []; cur = ""; }
        else if (ch === "\r") { /* skip */ }
        else cur += ch;
      }
    }
    if (cur.length > 0 || row.length > 0) { row.push(cur); rows.push(row); }
    return rows.filter((r) => r.some((c) => c.trim() !== ""));
  };

  const previewRows = (() => {
    if (!csvText.trim()) return [] as Record<string, string>[];
    const rows = parseCsv(csvText);
    if (rows.length === 0) return [];
    // Normalize headers to lowercase with underscores
    const header = rows[0].map((h) => h.trim().toLowerCase().replace(/ /g, "_"));
    return rows.slice(1).map((r) => {
      const obj: Record<string, string> = {};
      header.forEach((h, idx) => { obj[h] = (r[idx] ?? "").trim(); });
      return obj;
    });
  })();

  const getAvailableCode = (preferred: string, existingCodes: Set<string>) => {
    let char = preferred.charAt(0).toUpperCase();
    if (!existingCodes.has(char)) return char;
    for (let i = 65; i <= 90; i++) {
      if (!existingCodes.has(String.fromCharCode(i))) return String.fromCharCode(i);
    }
    for (let i = 48; i <= 57; i++) {
      if (!existingCodes.has(String.fromCharCode(i))) return String.fromCharCode(i);
    }
    return 'X';
  };

  const runImport = async () => {
    if (previewRows.length === 0) { toast.error("No rows to import"); return; }
    setImporting(true);

    let currentDepts = [...depts];
    let currentItems = [...items];

    // 1. Auto-create missing departments
    const csvLocations = Array.from(new Set(previewRows.map(r => r.location).filter(Boolean)));
    const deptCodes = new Set(currentDepts.map(d => d.code.toUpperCase()));
    for (const loc of csvLocations) {
      if (!currentDepts.find(d => d.name.toLowerCase() === loc.toLowerCase())) {
        const newCode = getAvailableCode(loc, deptCodes);
        const { data: newDep } = await supabase.from("departments").insert({ name: loc, code: newCode, is_storage: false }).select().single();
        if (newDep) {
          currentDepts.push(newDep);
          deptCodes.add(newCode);
        }
      }
    }

    // 2. Auto-create missing item types
    const csvDivisions = Array.from(new Set(previewRows.map(r => r.division).filter(Boolean)));
    const itemCodes = new Set(currentItems.map(i => i.code.toUpperCase()));
    for (const div of csvDivisions) {
      if (!currentItems.find(i => i.name.toLowerCase() === div.toLowerCase())) {
        const newCode = getAvailableCode(div, itemCodes);
        const { data: newItem } = await supabase.from("item_types").insert({ name: div, code: newCode }).select().single();
        if (newItem) {
          currentItems.push(newItem);
          itemCodes.add(newCode);
        }
      }
    }

    setDepts(currentDepts);
    setItems(currentItems);

    const deptByName = new Map(currentDepts.map((d) => [d.name.toLowerCase(), d]));
    const itemByName = new Map(currentItems.map((i) => [i.name.toLowerCase(), i]));
    const storageId = currentDepts.find((d) => d.is_storage)?.id;

    const errors: string[] = [];
    const valid: any[] = [];
    previewRows.forEach((row, idx) => {
      const lineNo = idx + 2; 
      const desc = row.description || "Unknown Asset";
      const name = desc; 
      const loc = (row.location ?? "").toLowerCase();
      const div = (row.division ?? "").toLowerCase();
      const serial = row.serial_number ?? "";
      const assetCode = row.asset_code ?? "";
      const imageUrl = row.image_url || null;

      if (!loc || !div) {
        errors.push(`Line ${lineNo}: missing Location or Division`);
        return;
      }

      const dept = deptByName.get(loc);
      const item = itemByName.get(div);
      if (!dept) { errors.push(`Line ${lineNo}: failed to resolve location "${row.location}"`); return; }
      if (!item) { errors.push(`Line ${lineNo}: failed to resolve division "${row.division}"`); return; }

      valid.push({
        name: name.slice(0, 120),
        description: desc.slice(0, 500) || null,
        serial_number: serial.slice(0, 80) || null,
        department_id: dept.id,
        item_type_id: item.id,
        current_location_id: storageId ?? dept.id,
        code: assetCode || "", // If empty, DB trigger will auto-generate
        image_url: imageUrl
      });
    });

    if (valid.length === 0) {
      setImporting(false);
      toast.error(errors[0] ?? "No valid rows");
      return;
    }

    // Insert in chunks of 100
    let inserted = 0;
    for (let i = 0; i < valid.length; i += 100) {
      const chunk = valid.slice(i, i + 100);
      const { error } = await supabase.from("assets").insert(chunk);
      if (error) {
        setImporting(false);
        toast.error(`Inserted ${inserted}, then failed: ${error.message}`);
        load();
        return;
      }
      inserted += chunk.length;
    }

    setImporting(false);
    setImportOpen(false);
    setCsvText("");
    if (errors.length > 0) {
      toast.success(`Imported ${inserted} · skipped ${errors.length}`, {
        description: errors.slice(0, 3).join(" · "),
      });
    } else {
      toast.success(`Imported ${inserted} asset${inserted === 1 ? "" : "s"}`);
    }
    load();
  };

  const statusColor: Record<string, string> = {
    available: "bg-primary/20 text-primary border-primary/40",
    signed_out: "bg-yellow-500/20 text-yellow-400 border-yellow-500/40",
    in_handover: "bg-blue-500/20 text-blue-400 border-blue-500/40",
    maintenance: "bg-orange-500/20 text-orange-400 border-orange-500/40",
    lost: "bg-destructive/20 text-destructive border-destructive/40",
    retired: "bg-muted text-muted-foreground border-border",
  };

  return (
    <div className="space-y-4 animate-fade-in">
      <div className="flex flex-col sm:flex-row gap-2 sm:items-center sm:justify-between">
        <div>
          <h1 className="font-display text-2xl text-primary glow">
            <span className="text-primary/60">$</span> ASSET REGISTRY
          </h1>
          <p className="font-mono text-xs text-muted-foreground mt-1 uppercase tracking-wider">
            // {filtered.length} record{filtered.length === 1 ? "" : "s"}
          </p>
        </div>
        {isAdmin && (
          <div className="flex gap-2">
            <Dialog open={open} onOpenChange={setOpen}>
              <DialogTrigger asChild>
                <Button className="bg-primary text-primary-foreground hover:bg-primary/90 font-mono uppercase tracking-wider">
                  <Plus size={16} className="mr-1" /> New Asset
                </Button>
              </DialogTrigger>
              <DialogContent className="bg-card border-primary/40">
                <DialogHeader><DialogTitle className="font-display text-primary">Register Asset</DialogTitle></DialogHeader>
                <div className="space-y-3">
                  <div><Label>Name</Label><Input value={name} onChange={(e) => setName(e.target.value)} maxLength={120} /></div>
                  <div><Label>Description</Label><Textarea value={description} onChange={(e) => setDescription(e.target.value)} maxLength={500} /></div>
                  <div><Label>Serial Number</Label><Input value={serial} onChange={(e) => setSerial(e.target.value)} maxLength={80} /></div>
                  <div className="grid grid-cols-2 gap-2">
                    <div>
                      <Label>Department</Label>
                      <Select value={deptId} onValueChange={setDeptId}>
                        <SelectTrigger><SelectValue placeholder="Select" /></SelectTrigger>
                        <SelectContent>{depts.map((d) => <SelectItem key={d.id} value={d.id}>{d.code} — {d.name}</SelectItem>)}</SelectContent>
                      </Select>
                    </div>
                    <div>
                      <Label>Item Type</Label>
                      <Select value={itemId} onValueChange={setItemId}>
                        <SelectTrigger><SelectValue placeholder="Select" /></SelectTrigger>
                        <SelectContent>{items.map((i) => <SelectItem key={i.id} value={i.id}>{i.code} — {i.name}</SelectItem>)}</SelectContent>
                      </Select>
                    </div>
                  </div>
                  <p className="text-xs text-muted-foreground">Code auto-generated: <span className="text-primary font-mono">{(depts.find(d=>d.id===deptId)?.code ?? "?")}{(items.find(i=>i.id===itemId)?.code ?? "?")}##</span></p>
                  <Button onClick={create} className="w-full bg-primary text-primary-foreground">Register</Button>
                </div>
              </DialogContent>
            </Dialog>

            <Dialog open={importOpen} onOpenChange={(o) => { setImportOpen(o); if (!o) setCsvText(""); }}>
              <DialogTrigger asChild>
                <Button variant="outline" className="border-primary/50 text-primary hover:bg-primary/10 font-mono uppercase tracking-wider">
                  <Upload size={16} className="mr-1" /> CSV Import
                </Button>
              </DialogTrigger>
              <DialogContent className="bg-card border-primary/40 max-w-2xl">
                <DialogHeader>
                  <DialogTitle className="font-display text-primary flex items-center gap-2">
                    <FileSpreadsheet size={18} /> Bulk Import Assets
                  </DialogTitle>
                </DialogHeader>
                <div className="space-y-4">
                  <div className="rounded border border-primary/20 bg-background/40 p-3 font-mono text-xs space-y-2">
                    <div className="text-primary uppercase tracking-widest">// expected columns</div>
                    <div className="text-muted-foreground">
                      <span className="text-primary">Asset Code</span>, <span className="text-primary">Division</span>, <span className="text-primary">Description</span>, Serial Number, <span className="text-primary">Location</span>
                    </div>
                    <div className="text-muted-foreground/70">
                      If locations or divisions do not exist in the system yet, they will be automatically created. Asset Code is optional.
                    </div>
                  </div>

                  <div className="flex flex-wrap gap-2">
                    <Button type="button" variant="outline" size="sm" onClick={downloadTemplate} className="border-primary/40 font-mono text-xs">
                      <Download size={14} className="mr-1" /> Download template
                    </Button>
                    <label className="inline-flex">
                      <input
                        type="file"
                        accept=".csv,text/csv"
                        className="hidden"
                        onChange={(e) => { const f = e.target.files?.[0]; if (f) onCsvFile(f); e.target.value = ""; }}
                      />
                      <span className="inline-flex items-center cursor-pointer rounded border border-primary/40 px-3 py-1.5 text-xs font-mono uppercase tracking-wider text-primary hover:bg-primary/10">
                        <Upload size={14} className="mr-1" /> Choose file
                      </span>
                    </label>
                  </div>

                  <div>
                    <Label className="font-mono text-xs uppercase tracking-wider">CSV content</Label>
                    <Textarea
                      value={csvText}
                      onChange={(e) => setCsvText(e.target.value)}
                      placeholder={csvSample}
                      rows={6}
                      className="font-mono text-xs"
                    />
                  </div>

                  {previewRows.length > 0 && (
                    <div className="rounded border border-primary/20">
                      <div className="border-b border-primary/20 px-3 py-2 font-mono text-[11px] uppercase tracking-widest text-primary">
                        &gt; Preview · {previewRows.length} row{previewRows.length === 1 ? "" : "s"}
                      </div>
                      <div className="max-h-48 overflow-auto">
                        <table className="w-full font-mono text-xs">
                          <thead className="bg-primary/5 text-muted-foreground uppercase text-[10px]">
                            <tr>
                              <th className="px-2 py-1 text-left">Code</th>
                              <th className="px-2 py-1 text-left">Description</th>
                              <th className="px-2 py-1 text-left">Loc</th>
                              <th className="px-2 py-1 text-left">Div</th>
                              <th className="px-2 py-1 text-left">Serial</th>
                            </tr>
                          </thead>
                          <tbody>
                            {previewRows.slice(0, 50).map((r, idx) => (
                              <tr key={idx} className="border-t border-primary/10">
                                <td className="px-2 py-1 text-primary truncate max-w-[100px]">{r.asset_code}</td>
                                <td className="px-2 py-1 text-foreground/80 truncate max-w-[200px]">{r.description}</td>
                                <td className="px-2 py-1 text-foreground/80">{r.location}</td>
                                <td className="px-2 py-1 text-foreground/80">{r.division}</td>
                                <td className="px-2 py-1 text-muted-foreground">{r.serial_number}</td>
                              </tr>
                            ))}
                          </tbody>
                        </table>
                      </div>
                    </div>
                  )}

                  <Button
                    onClick={runImport}
                    disabled={importing || previewRows.length === 0}
                    className="w-full bg-primary text-primary-foreground font-mono uppercase tracking-wider"
                  >
                    {importing ? "Importing…" : `Import ${previewRows.length || ""} asset${previewRows.length === 1 ? "" : "s"}`}
                  </Button>
                </div>
              </DialogContent>
            </Dialog>
          </div>
        )}
      </div>

      <div className="flex flex-col sm:flex-row gap-2">
        <div className="relative flex-1">
          <Search className="absolute left-3 top-2.5 text-muted-foreground" size={16} />
          <Input value={q} onChange={(e) => setQ(e.target.value)} placeholder="Search code or name…" className="pl-9 font-mono" />
        </div>
        <Select value={statusFilter} onValueChange={setStatusFilter}>
          <SelectTrigger className="sm:w-44"><SelectValue placeholder="Status" /></SelectTrigger>
          <SelectContent>
            <SelectItem value="all">All Statuses</SelectItem>
            <SelectItem value="available">Available</SelectItem>
            <SelectItem value="signed_out">Sign Out</SelectItem>
            <SelectItem value="maintenance">Maintenance</SelectItem>
            <SelectItem value="lost">Lost</SelectItem>
            <SelectItem value="retired">Damaged</SelectItem>
          </SelectContent>
        </Select>
      </div>

      {/* Table */}
      <div className="rounded border border-primary/30 bg-card/30 overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full font-mono text-sm">
            <thead>
              <tr className="border-b border-primary/30 text-left text-[11px] uppercase tracking-widest text-muted-foreground">
                <th className="px-4 py-3 font-normal">Name</th>
                <th className="px-4 py-3 font-normal">Tag</th>
                <th className="px-4 py-3 font-normal">Category</th>
                <th className="px-4 py-3 font-normal">Status</th>
                <th className="px-4 py-3 font-normal">Location</th>
                {isAdmin && <th className="px-4 py-3 font-normal w-10" />}
              </tr>
            </thead>
            <tbody className="divide-y divide-primary/10">
              {filtered.length === 0 && (
                <tr><td colSpan={isAdmin ? 6 : 5} className="px-4 py-12 text-center text-muted-foreground/70">// no records found</td></tr>
              )}
              {filtered.map((a) => {
                const itemType = items.find((i) => i.id === a.item_type_id);
                const dept = depts.find((d) => d.id === (a.current_location_id ?? a.department_id));
                return (
                  <tr key={a.id} className="hover:bg-primary/5 transition-colors group">
                    <td className="px-4 py-3 text-primary glow-soft truncate max-w-[220px]">
                      <Link to={`/assets/${a.id}`} className="hover:underline flex items-center gap-2">
                        {a.name}
                        <ExternalLink size={12} className="opacity-0 group-hover:opacity-50 transition-opacity" />
                      </Link>
                    </td>
                    <td className="px-4 py-3 text-foreground/80">
                      <Link to={`/assets/${a.id}`} className="hover:text-primary transition-colors">
                        {a.code}
                      </Link>
                    </td>
                    <td className="px-4 py-3 text-muted-foreground">{itemType?.name ?? "—"}</td>
                    <td className="px-4 py-3">
                      <Badge variant="outline" className={cn("uppercase text-[10px] tracking-widest", statusColor[a.status])}>
                        {a.status === "signed_out" ? "Sign Out" : a.status === "retired" ? "Damaged" : a.status.replace("_", " ")}
                      </Badge>
                    </td>
                    <td className="px-4 py-3 text-muted-foreground truncate max-w-[200px]">
                      {dept?.name ?? "—"}
                      {a.current_holder && <span className="text-foreground/60"> · {holders[a.current_holder] ?? "?"}</span>}
                    </td>
                    {isAdmin && (
                      <td className="px-4 py-3">
                        <Button size="sm" variant="ghost" onClick={() => remove(a.id)} className="text-destructive hover:bg-destructive/10 h-7 w-7 p-0">
                          <Trash2 size={14} />
                        </Button>
                      </td>
                    )}
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
