import { useEffect, useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/contexts/AuthContext";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Card } from "@/components/ui/card";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { toast } from "sonner";
import { Plus, Search, Trash2, Upload, Download, FileSpreadsheet } from "lucide-react";
import { cn } from "@/lib/utils";

interface Asset {
  id: string; code: string; name: string; status: string;
  description: string | null; serial_number: string | null;
  department_id: string; item_type_id: string;
  current_holder: string | null; current_location_id: string | null;
}
interface Dept { id: string; code: string; name: string; is_storage?: boolean; }
interface ItemType { id: string; code: string; name: string; }
interface Holder { id: string; display_name: string; }

export default function Assets() {
  const { isAdmin } = useAuth();
  const [assets, setAssets] = useState<Asset[]>([]);
  const [depts, setDepts] = useState<Dept[]>([]);
  const [items, setItems] = useState<ItemType[]>([]);
  const [holders, setHolders] = useState<Record<string, string>>({});
  const [q, setQ] = useState("");
  const [statusFilter, setStatusFilter] = useState<string>("all");
  const [open, setOpen] = useState(false);
  const [importOpen, setImportOpen] = useState(false);
  const [csvText, setCsvText] = useState("");
  const [importing, setImporting] = useState(false);

  // form
  const [name, setName] = useState("");
  const [description, setDescription] = useState("");
  const [serial, setSerial] = useState("");
  const [deptId, setDeptId] = useState("");
  const [itemId, setItemId] = useState("");

  const load = async () => {
    const [{ data: a }, { data: d }, { data: i }, { data: p }] = await Promise.all([
      supabase.from("assets").select("*").order("code"),
      supabase.from("departments").select("*").order("name"),
      supabase.from("item_types").select("*").order("name"),
      supabase.from("profiles").select("id, display_name"),
    ]);
    setAssets(a ?? []);
    setDepts(d ?? []);
    setItems(i ?? []);
    setHolders(Object.fromEntries((p ?? []).map((x: Holder) => [x.id, x.display_name])));
  };
  useEffect(() => { load(); }, []);

  const filtered = assets.filter((a) => {
    const matchesQ = !q || a.code.toLowerCase().includes(q.toLowerCase()) || a.name.toLowerCase().includes(q.toLowerCase());
    const matchesS = statusFilter === "all" || a.status === statusFilter;
    return matchesQ && matchesS;
  });

  const create = async () => {
    if (!name || !deptId || !itemId) {
      toast.error("Name, department and item type are required");
      return;
    }
    const dept = depts.find((d) => d.id === deptId);
    const { error } = await supabase.from("assets").insert({
      name, description: description || null, serial_number: serial || null,
      department_id: deptId, item_type_id: itemId,
      current_location_id: depts.find((d) => d.is_storage)?.id ?? deptId,
      code: "", // generated by trigger
    } as any);
    if (error) { toast.error(error.message); return; }
    toast.success(`Asset registered in ${dept?.name}`);
    setOpen(false);
    setName(""); setDescription(""); setSerial(""); setDeptId(""); setItemId("");
    load();
  };

  const remove = async (id: string) => {
    if (!confirm("Delete this asset permanently?")) return;
    const { error } = await supabase.from("assets").delete().eq("id", id);
    if (error) { toast.error(error.message); return; }
    toast.success("Asset deleted");
    load();
  };

  // ----- CSV BULK IMPORT -----
  const csvHeader = "name,department_code,item_type_code,description,serial_number";
  const csvSample = `${csvHeader}\nMacBook Pro 14",T,L,Engineering laptop,SN12345\niPad Pro 12.9",T,T,,SN67890`;

  const downloadTemplate = () => {
    const blob = new Blob([csvSample], { type: "text/csv" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "assets-template.csv";
    a.click();
    URL.revokeObjectURL(url);
  };

  const onCsvFile = async (file: File) => {
    if (file.size > 2 * 1024 * 1024) {
      toast.error("File too large (max 2MB)");
      return;
    }
    const text = await file.text();
    setCsvText(text);
  };

  // Tiny CSV parser supporting quoted fields with commas
  const parseCsv = (text: string): string[][] => {
    const rows: string[][] = [];
    let row: string[] = [];
    let cur = "";
    let inQuotes = false;
    for (let i = 0; i < text.length; i++) {
      const ch = text[i];
      if (inQuotes) {
        if (ch === '"' && text[i + 1] === '"') { cur += '"'; i++; }
        else if (ch === '"') { inQuotes = false; }
        else { cur += ch; }
      } else {
        if (ch === '"') inQuotes = true;
        else if (ch === ",") { row.push(cur); cur = ""; }
        else if (ch === "\n") { row.push(cur); rows.push(row); row = []; cur = ""; }
        else if (ch === "\r") { /* skip */ }
        else cur += ch;
      }
    }
    if (cur.length > 0 || row.length > 0) { row.push(cur); rows.push(row); }
    return rows.filter((r) => r.some((c) => c.trim() !== ""));
  };

  const previewRows = (() => {
    if (!csvText.trim()) return [] as Record<string, string>[];
    const rows = parseCsv(csvText);
    if (rows.length === 0) return [];
    const header = rows[0].map((h) => h.trim().toLowerCase());
    return rows.slice(1).map((r) => {
      const obj: Record<string, string> = {};
      header.forEach((h, idx) => { obj[h] = (r[idx] ?? "").trim(); });
      return obj;
    });
  })();

  const runImport = async () => {
    if (previewRows.length === 0) { toast.error("No rows to import"); return; }
    setImporting(true);
    const deptByCode = new Map(depts.map((d) => [d.code.toUpperCase(), d]));
    const itemByCode = new Map(items.map((i) => [i.code.toUpperCase(), i]));
    const storageId = depts.find((d) => d.is_storage)?.id;

    const errors: string[] = [];
    const valid: any[] = [];
    previewRows.forEach((row, idx) => {
      const lineNo = idx + 2; // header is line 1
      const name = row.name?.trim();
      const dCode = (row.department_code ?? "").trim().toUpperCase();
      const iCode = (row.item_type_code ?? "").trim().toUpperCase();
      if (!name || !dCode || !iCode) {
        errors.push(`Line ${lineNo}: missing name / department_code / item_type_code`);
        return;
      }
      const dept = deptByCode.get(dCode);
      const item = itemByCode.get(iCode);
      if (!dept) { errors.push(`Line ${lineNo}: unknown department_code "${dCode}"`); return; }
      if (!item) { errors.push(`Line ${lineNo}: unknown item_type_code "${iCode}"`); return; }
      valid.push({
        name: name.slice(0, 120),
        description: (row.description || "").slice(0, 500) || null,
        serial_number: (row.serial_number || "").slice(0, 80) || null,
        department_id: dept.id,
        item_type_id: item.id,
        current_location_id: storageId ?? dept.id,
        code: "", // generated by trigger
      });
    });

    if (valid.length === 0) {
      setImporting(false);
      toast.error(errors[0] ?? "No valid rows");
      return;
    }

    // Insert in chunks of 100
    let inserted = 0;
    for (let i = 0; i < valid.length; i += 100) {
      const chunk = valid.slice(i, i + 100);
      const { error } = await supabase.from("assets").insert(chunk);
      if (error) {
        setImporting(false);
        toast.error(`Inserted ${inserted}, then failed: ${error.message}`);
        load();
        return;
      }
      inserted += chunk.length;
    }

    setImporting(false);
    setImportOpen(false);
    setCsvText("");
    if (errors.length > 0) {
      toast.success(`Imported ${inserted} · skipped ${errors.length}`, {
        description: errors.slice(0, 3).join(" · "),
      });
    } else {
      toast.success(`Imported ${inserted} asset${inserted === 1 ? "" : "s"}`);
    }
    load();
  };

  const statusColor: Record<string, string> = {
    available: "bg-primary/20 text-primary border-primary/40",
    signed_out: "bg-yellow-500/20 text-yellow-400 border-yellow-500/40",
    in_handover: "bg-blue-500/20 text-blue-400 border-blue-500/40",
    maintenance: "bg-orange-500/20 text-orange-400 border-orange-500/40",
    lost: "bg-destructive/20 text-destructive border-destructive/40",
    retired: "bg-muted text-muted-foreground border-border",
  };

  return (
    <div className="space-y-4 animate-fade-in">
      <div className="flex flex-col sm:flex-row gap-2 sm:items-center sm:justify-between">
        <div>
          <h1 className="font-display text-2xl text-primary glow">
            <span className="text-primary/60">$</span> ASSET REGISTRY
          </h1>
          <p className="font-mono text-xs text-muted-foreground mt-1 uppercase tracking-wider">
            // {filtered.length} record{filtered.length === 1 ? "" : "s"}
          </p>
        </div>
        {isAdmin && (
          <Dialog open={open} onOpenChange={setOpen}>
            <DialogTrigger asChild>
              <Button className="bg-primary text-primary-foreground hover:bg-primary/90 font-mono uppercase tracking-wider">
                <Plus size={16} className="mr-1" /> New Asset
              </Button>
            </DialogTrigger>
            <DialogContent className="bg-card border-primary/40">
              <DialogHeader><DialogTitle className="font-display text-primary">Register Asset</DialogTitle></DialogHeader>
              <div className="space-y-3">
                <div><Label>Name</Label><Input value={name} onChange={(e) => setName(e.target.value)} maxLength={120} /></div>
                <div><Label>Description</Label><Textarea value={description} onChange={(e) => setDescription(e.target.value)} maxLength={500} /></div>
                <div><Label>Serial Number</Label><Input value={serial} onChange={(e) => setSerial(e.target.value)} maxLength={80} /></div>
                <div className="grid grid-cols-2 gap-2">
                  <div>
                    <Label>Department</Label>
                    <Select value={deptId} onValueChange={setDeptId}>
                      <SelectTrigger><SelectValue placeholder="Select" /></SelectTrigger>
                      <SelectContent>{depts.map((d) => <SelectItem key={d.id} value={d.id}>{d.code} — {d.name}</SelectItem>)}</SelectContent>
                    </Select>
                  </div>
                  <div>
                    <Label>Item Type</Label>
                    <Select value={itemId} onValueChange={setItemId}>
                      <SelectTrigger><SelectValue placeholder="Select" /></SelectTrigger>
                      <SelectContent>{items.map((i) => <SelectItem key={i.id} value={i.id}>{i.code} — {i.name}</SelectItem>)}</SelectContent>
                    </Select>
                  </div>
                </div>
                <p className="text-xs text-muted-foreground">Code auto-generated: <span className="text-primary font-mono">{(depts.find(d=>d.id===deptId)?.code ?? "?")}{(items.find(i=>i.id===itemId)?.code ?? "?")}##</span></p>
                <Button onClick={create} className="w-full bg-primary text-primary-foreground">Register</Button>
              </div>
            </DialogContent>
          </Dialog>
        )}
      </div>

      <div className="flex flex-col sm:flex-row gap-2">
        <div className="relative flex-1">
          <Search className="absolute left-3 top-2.5 text-muted-foreground" size={16} />
          <Input value={q} onChange={(e) => setQ(e.target.value)} placeholder="Search code or name…" className="pl-9 font-mono" />
        </div>
        <Select value={statusFilter} onValueChange={setStatusFilter}>
          <SelectTrigger className="sm:w-44"><SelectValue /></SelectTrigger>
          <SelectContent>
            <SelectItem value="all">All statuses</SelectItem>
            <SelectItem value="available">Available</SelectItem>
            <SelectItem value="signed_out">Signed out</SelectItem>
            <SelectItem value="in_handover">In handover</SelectItem>
            <SelectItem value="maintenance">Maintenance</SelectItem>
            <SelectItem value="lost">Lost</SelectItem>
            <SelectItem value="retired">Retired</SelectItem>
          </SelectContent>
        </Select>
      </div>

      {/* Table */}
      <div className="rounded border border-primary/30 bg-card/30 overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full font-mono text-sm">
            <thead>
              <tr className="border-b border-primary/30 text-left text-[11px] uppercase tracking-widest text-muted-foreground">
                <th className="px-4 py-3 font-normal">Name</th>
                <th className="px-4 py-3 font-normal">Tag</th>
                <th className="px-4 py-3 font-normal">Category</th>
                <th className="px-4 py-3 font-normal">Status</th>
                <th className="px-4 py-3 font-normal">Location</th>
                {isAdmin && <th className="px-4 py-3 font-normal w-10" />}
              </tr>
            </thead>
            <tbody className="divide-y divide-primary/10">
              {filtered.length === 0 && (
                <tr><td colSpan={isAdmin ? 6 : 5} className="px-4 py-12 text-center text-muted-foreground/70">// no records found</td></tr>
              )}
              {filtered.map((a) => {
                const itemType = items.find((i) => i.id === a.item_type_id);
                const dept = depts.find((d) => d.id === (a.current_location_id ?? a.department_id));
                return (
                  <tr key={a.id} className="hover:bg-primary/5 transition-colors">
                    <td className="px-4 py-3 text-primary glow-soft truncate max-w-[220px]">{a.name}</td>
                    <td className="px-4 py-3 text-foreground/80">{a.code}</td>
                    <td className="px-4 py-3 text-muted-foreground">{itemType?.name ?? "—"}</td>
                    <td className="px-4 py-3">
                      <Badge variant="outline" className={cn("uppercase text-[10px] tracking-widest", statusColor[a.status])}>
                        {a.status.replace("_", " ")}
                      </Badge>
                    </td>
                    <td className="px-4 py-3 text-muted-foreground truncate max-w-[200px]">
                      {dept?.name ?? "—"}
                      {a.current_holder && <span className="text-foreground/60"> · {holders[a.current_holder] ?? "?"}</span>}
                    </td>
                    {isAdmin && (
                      <td className="px-4 py-3">
                        <Button size="sm" variant="ghost" onClick={() => remove(a.id)} className="text-destructive hover:bg-destructive/10 h-7 w-7 p-0">
                          <Trash2 size={14} />
                        </Button>
                      </td>
                    )}
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
