import { useEffect, useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/contexts/AuthContext";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Card } from "@/components/ui/card";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { toast } from "sonner";
import { Plus, Search, Trash2 } from "lucide-react";

interface Asset {
  id: string; code: string; name: string; status: string;
  description: string | null; serial_number: string | null;
  department_id: string; item_type_id: string;
  current_holder: string | null; current_location_id: string | null;
}
interface Dept { id: string; code: string; name: string; }
interface ItemType { id: string; code: string; name: string; }
interface Holder { id: string; display_name: string; }

export default function Assets() {
  const { isAdmin } = useAuth();
  const [assets, setAssets] = useState<Asset[]>([]);
  const [depts, setDepts] = useState<Dept[]>([]);
  const [items, setItems] = useState<ItemType[]>([]);
  const [holders, setHolders] = useState<Record<string, string>>({});
  const [q, setQ] = useState("");
  const [statusFilter, setStatusFilter] = useState<string>("all");
  const [open, setOpen] = useState(false);

  // form
  const [name, setName] = useState("");
  const [description, setDescription] = useState("");
  const [serial, setSerial] = useState("");
  const [deptId, setDeptId] = useState("");
  const [itemId, setItemId] = useState("");

  const load = async () => {
    const [{ data: a }, { data: d }, { data: i }, { data: p }] = await Promise.all([
      supabase.from("assets").select("*").order("code"),
      supabase.from("departments").select("*").order("name"),
      supabase.from("item_types").select("*").order("name"),
      supabase.from("profiles").select("id, display_name"),
    ]);
    setAssets(a ?? []);
    setDepts(d ?? []);
    setItems(i ?? []);
    setHolders(Object.fromEntries((p ?? []).map((x: Holder) => [x.id, x.display_name])));
  };
  useEffect(() => { load(); }, []);

  const filtered = assets.filter((a) => {
    const matchesQ = !q || a.code.toLowerCase().includes(q.toLowerCase()) || a.name.toLowerCase().includes(q.toLowerCase());
    const matchesS = statusFilter === "all" || a.status === statusFilter;
    return matchesQ && matchesS;
  });

  const create = async () => {
    if (!name || !deptId || !itemId) {
      toast.error("Name, department and item type are required");
      return;
    }
    const dept = depts.find((d) => d.id === deptId);
    const { error } = await supabase.from("assets").insert({
      name, description: description || null, serial_number: serial || null,
      department_id: deptId, item_type_id: itemId,
      current_location_id: depts.find((d) => d.is_storage)?.id ?? deptId,
      code: "", // generated by trigger
    } as any);
    if (error) { toast.error(error.message); return; }
    toast.success(`Asset registered in ${dept?.name}`);
    setOpen(false);
    setName(""); setDescription(""); setSerial(""); setDeptId(""); setItemId("");
    load();
  };

  const remove = async (id: string) => {
    if (!confirm("Delete this asset permanently?")) return;
    const { error } = await supabase.from("assets").delete().eq("id", id);
    if (error) { toast.error(error.message); return; }
    toast.success("Asset deleted");
    load();
  };

  const statusColor: Record<string, string> = {
    available: "bg-primary/20 text-primary border-primary/40",
    signed_out: "bg-yellow-500/20 text-yellow-400 border-yellow-500/40",
    in_handover: "bg-blue-500/20 text-blue-400 border-blue-500/40",
    maintenance: "bg-orange-500/20 text-orange-400 border-orange-500/40",
    lost: "bg-destructive/20 text-destructive border-destructive/40",
    retired: "bg-muted text-muted-foreground border-border",
  };

  return (
    <div className="space-y-4 animate-fade-in">
      <div className="flex flex-col sm:flex-row gap-2 sm:items-center sm:justify-between">
        <h1 className="font-display text-2xl text-primary glow">// Asset Registry</h1>
        {isAdmin && (
          <Dialog open={open} onOpenChange={setOpen}>
            <DialogTrigger asChild>
              <Button className="bg-primary text-primary-foreground hover:bg-primary/90"><Plus size={16} className="mr-1" /> New Asset</Button>
            </DialogTrigger>
            <DialogContent className="bg-card border-primary/40">
              <DialogHeader><DialogTitle className="font-display text-primary">Register Asset</DialogTitle></DialogHeader>
              <div className="space-y-3">
                <div><Label>Name</Label><Input value={name} onChange={(e) => setName(e.target.value)} maxLength={120} /></div>
                <div><Label>Description</Label><Textarea value={description} onChange={(e) => setDescription(e.target.value)} maxLength={500} /></div>
                <div><Label>Serial Number</Label><Input value={serial} onChange={(e) => setSerial(e.target.value)} maxLength={80} /></div>
                <div className="grid grid-cols-2 gap-2">
                  <div>
                    <Label>Department</Label>
                    <Select value={deptId} onValueChange={setDeptId}>
                      <SelectTrigger><SelectValue placeholder="Select" /></SelectTrigger>
                      <SelectContent>{depts.map((d) => <SelectItem key={d.id} value={d.id}>{d.code} — {d.name}</SelectItem>)}</SelectContent>
                    </Select>
                  </div>
                  <div>
                    <Label>Item Type</Label>
                    <Select value={itemId} onValueChange={setItemId}>
                      <SelectTrigger><SelectValue placeholder="Select" /></SelectTrigger>
                      <SelectContent>{items.map((i) => <SelectItem key={i.id} value={i.id}>{i.code} — {i.name}</SelectItem>)}</SelectContent>
                    </Select>
                  </div>
                </div>
                <p className="text-xs text-muted-foreground">Code auto-generated: <span className="text-primary font-mono">{(depts.find(d=>d.id===deptId)?.code ?? "?")}{(items.find(i=>i.id===itemId)?.code ?? "?")}##</span></p>
                <Button onClick={create} className="w-full bg-primary text-primary-foreground">Register</Button>
              </div>
            </DialogContent>
          </Dialog>
        )}
      </div>

      <div className="flex flex-col sm:flex-row gap-2">
        <div className="relative flex-1">
          <Search className="absolute left-3 top-2.5 text-muted-foreground" size={16} />
          <Input value={q} onChange={(e) => setQ(e.target.value)} placeholder="Search code or name…" className="pl-9 font-mono" />
        </div>
        <Select value={statusFilter} onValueChange={setStatusFilter}>
          <SelectTrigger className="sm:w-44"><SelectValue /></SelectTrigger>
          <SelectContent>
            <SelectItem value="all">All statuses</SelectItem>
            <SelectItem value="available">Available</SelectItem>
            <SelectItem value="signed_out">Signed out</SelectItem>
            <SelectItem value="in_handover">In handover</SelectItem>
            <SelectItem value="maintenance">Maintenance</SelectItem>
            <SelectItem value="lost">Lost</SelectItem>
            <SelectItem value="retired">Retired</SelectItem>
          </SelectContent>
        </Select>
      </div>

      <div className="grid gap-2">
        {filtered.length === 0 && (
          <Card className="bg-card/30 border-primary/20 p-6 text-center text-muted-foreground font-mono">// no records</Card>
        )}
        {filtered.map((a) => (
          <Card key={a.id} className="bg-card/40 border-primary/20 p-3 flex items-center gap-3 hover:border-primary/60 transition">
            <div className="font-display text-lg text-primary glow-soft min-w-[60px]">{a.code}</div>
            <div className="flex-1 min-w-0">
              <div className="font-mono text-sm truncate">{a.name}</div>
              <div className="text-xs text-muted-foreground truncate">
                {a.serial_number && <>SN: {a.serial_number} · </>}
                {a.current_holder && <>Held by {holders[a.current_holder] ?? "?"}</>}
              </div>
            </div>
            <Badge variant="outline" className={statusColor[a.status]}>{a.status.replace("_", " ")}</Badge>
            {isAdmin && (
              <Button size="sm" variant="ghost" onClick={() => remove(a.id)} className="text-destructive hover:bg-destructive/10">
                <Trash2 size={14} />
              </Button>
            )}
          </Card>
        ))}
      </div>
    </div>
  );
}
